// <auto-generated />
using System;
using CRUD_FluentAPI_.NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_FluentAPI_.NET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240831201454_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CRUD_FluentAPI_.NET.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Tenetur omnis asperiores voluptas sint.",
                            Nombre = "Jewelery",
                            Peso = 0
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Est id ut tenetur unde.",
                            Nombre = "Health",
                            Peso = 0
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Ut quis nesciunt eaque eum.",
                            Nombre = "Automotive",
                            Peso = 0
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Sed libero repudiandae repudiandae labore.",
                            Nombre = "Garden",
                            Peso = 0
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Libero nam molestiae dicta tenetur.",
                            Nombre = "Garden",
                            Peso = 0
                        });
                });

            modelBuilder.Entity("CRUD_FluentAPI_.NET.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tareas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 3,
                            Descripcion = "Nam voluptatibus sint nam aut voluptatem quidem earum enim sunt. Sunt ea occaecati ut sequi dolor. Eveniet natus temporibus rerum cum voluptatem corrupti assumenda aliquam quia. Totam autem molestias doloremque id sit laboriosam quasi iste quos. Maxime exercitationem aliquam. Et consequatur aut doloremque voluptate eum dolor aut eos et.",
                            Estado = false,
                            FechaCreacion = new DateTime(2024, 5, 8, 4, 54, 10, 917, DateTimeKind.Local).AddTicks(3852),
                            Prioridad = 3,
                            Titulo = "Inventore voluptatem culpa."
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 5,
                            Descripcion = "Odio non quas ea mollitia consectetur odit voluptas eveniet nesciunt. Repellat vitae sunt quos soluta quas aliquam corrupti. Aut est earum totam officia consectetur aperiam et atque commodi.",
                            Estado = true,
                            FechaCreacion = new DateTime(2023, 10, 20, 9, 31, 18, 308, DateTimeKind.Local).AddTicks(3739),
                            Prioridad = 3,
                            Titulo = "Ab quidem et."
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 5,
                            Descripcion = "Suscipit ab eaque nobis consequuntur explicabo aut aut est. Sint dolor sunt est doloribus. Accusamus eum qui architecto.",
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 3, 21, 17, 56, 38, 814, DateTimeKind.Local).AddTicks(3823),
                            Prioridad = 1,
                            Titulo = "Deserunt blanditiis exercitationem."
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            Descripcion = "Laudantium veniam pariatur ut eum animi. Et voluptatem autem quia eos ut iure dolorum. Itaque quia aperiam.",
                            Estado = false,
                            FechaCreacion = new DateTime(2023, 11, 14, 7, 30, 10, 424, DateTimeKind.Local).AddTicks(5558),
                            Prioridad = 0,
                            Titulo = "Provident sapiente porro."
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 2,
                            Descripcion = "Aut quis et ut rerum reprehenderit aut. Saepe expedita enim provident cupiditate voluptatibus enim rerum aut est. Vero natus accusamus porro esse reprehenderit aperiam totam maiores.",
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 7, 27, 14, 13, 9, 604, DateTimeKind.Local).AddTicks(8008),
                            Prioridad = 1,
                            Titulo = "Mollitia eligendi eveniet."
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Descripcion = "Quibusdam facere nam aut esse sunt explicabo. Aliquid quia fugit ut recusandae animi. Corrupti facere magni eum pariatur aut mollitia maxime fugiat et. Cumque cumque eaque aperiam. Ipsam velit ut et et.",
                            Estado = false,
                            FechaCreacion = new DateTime(2023, 10, 31, 20, 59, 46, 395, DateTimeKind.Local).AddTicks(7657),
                            Prioridad = 0,
                            Titulo = "Quasi aut sint."
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 5,
                            Descripcion = "Autem odit consequatur est distinctio architecto et accusamus. Possimus placeat voluptas aut ipsum. Ipsam rerum et rem ratione vero culpa consequatur commodi ipsa.",
                            Estado = true,
                            FechaCreacion = new DateTime(2023, 12, 17, 20, 18, 1, 827, DateTimeKind.Local).AddTicks(8249),
                            Prioridad = 2,
                            Titulo = "Amet dolor qui."
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            Descripcion = "Sunt maiores est explicabo. Itaque autem sequi ipsam facere quo iusto tenetur est. Nihil perspiciatis voluptatem officia ducimus placeat culpa accusamus. Voluptatibus qui atque eveniet saepe. Ab rerum nulla quia.",
                            Estado = false,
                            FechaCreacion = new DateTime(2024, 4, 1, 16, 53, 47, 425, DateTimeKind.Local).AddTicks(7191),
                            Prioridad = 1,
                            Titulo = "Omnis ratione qui."
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 1,
                            Descripcion = "Id maxime nam eos sit. Voluptatem eveniet ratione delectus necessitatibus placeat quis nam. Quidem ut eos tempore est quia ipsam. Sapiente dolores et est quidem quis facilis est. Omnis molestias sint cupiditate enim minima et similique provident fugit.",
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 5, 30, 6, 35, 25, 745, DateTimeKind.Local).AddTicks(3639),
                            Prioridad = 0,
                            Titulo = "Vero nihil et."
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 2,
                            Descripcion = "Mollitia omnis dolores. Qui ut expedita voluptatum nobis reiciendis quaerat ullam officiis. Accusamus facere eos et eveniet ipsa. Ut illo non sunt tenetur deleniti molestias aspernatur.",
                            Estado = true,
                            FechaCreacion = new DateTime(2024, 4, 23, 14, 10, 41, 107, DateTimeKind.Local).AddTicks(1746),
                            Prioridad = 0,
                            Titulo = "Accusamus commodi aut."
                        });
                });

            modelBuilder.Entity("CRUD_FluentAPI_.NET.Models.Tarea", b =>
                {
                    b.HasOne("CRUD_FluentAPI_.NET.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CRUD_FluentAPI_.NET.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
